version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: dev
    ignore:
      - dependency-name: framer-motion
        versions:
          - 4.1.2
          - 4.1.3
      - dependency-name: date-fns
        versions:
          - 2.17.0
          - 2.20.1
      - dependency-name: webpack
        versions:
          - 5.24.2
          - 5.24.3
          - 5.27.1
          - 5.28.0
      - dependency-name: next-sitemap
        versions:
          - 1.6.3
          - 1.6.9
      - dependency-name: next-seo
        versions:
          - 4.22.0
      - dependency-name: eslint
        versions:
          - 7.22.0
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions:
          - 4.14.2
          - 4.15.2
          - 4.16.1
      - dependency-name: typescript
        versions:
          - 4.2.2
      - dependency-name: "@babel/core"
        versions:
          - 7.12.13
          - 7.13.8
      - dependency-name: mjml
        versions:
          - 4.8.1
      - dependency-name: "@next/mdx"
        versions:
          - 10.0.7
      - dependency-name: react-use
        versions:
          - 17.1.0
      - dependency-name: "@types/node"
        versions:
          - 14.14.25
      - dependency-name: "@types/react"
        versions:
          - 17.0.1
